### ISSUE TITLE
Failed to import - node-fetch-native

### ISSUE THREAD

**Issue by paulshen** [ije/esm.sh#422]
## Failing module

```js
import 'https://esm.sh/@notionhq/client'
import 'https://esm.sh/@tensorflow/tfjs'
```

## Error message

These modules have node-fetch-native as a dependency. However, https://esm.sh/v95/node-fetch-native@0.1.3/es2022/node-fetch-native.js returns a 500

```
/* esm.sh - error */
throw new Error("[esm.sh] " + "npm: can't get metadata of package 'process/browser' (405 Method Not Allowed: {\"code\":\"MethodNotAllowedError\",\"message\":\"GET is not allowed\"})");
export default null;
```

## Additional info

- **esm.sh version**: 95
- **Browser version**: 
Arc Version 0.69.0 (34772)
Chromium Engine Version 105.0.5195.127

**Comment by ije** [comment]
this should be fixed in last update

**Comment by paulshen** [comment]
@ije Awesome thank you! That loads fine now.

Unfortunately, the parent packages still don't load because `node-fetch-native` depends on `worker_threads`. I see a request to https://esm.sh/error.js?type=unsupported-nodejs-builtin-module&name=worker_threads&importer=node-fetch-native. It'd be great to get this working in the browser.

Thanks again for your great work!
